# Generated by Django 5.1.4 on 2025-09-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_bid_address_bid_latitude_bid_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='longitude',
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
